# environment.yml
name: MonteCarlo_book
channels:
  - conda-forge
dependencies:
  - python=3.12.2
  - numpy=2.2.3
  - matplotlib=3.10.0
  - scipy=1.15.1
  - pandas
  - tabulate
  - pip:
      - pynverse==0.1.4.6
